### ISSUE TITLE
Please add support for web

### ISSUE THREAD

**Issue by topex-psy** [fluttercommunity/flutter_launcher_icons#310] opened 2021-12-12 10:31 UTC
### :speech_balloon: Description
Please make this plugin also change set of favicons used in flutter web.

### :question: Platform
Web

**Comment by dvorapa** [comment] 2021-12-21 11:09
Duplicate of #126

**Comment by RatakondalaArun** [comment] 2022-08-01 16:07
This feature is added in #374

**Closed by RatakondalaArun** 2022-08-01 16:07 UTC
Labels: improvement
