### ISSUE TITLE
"Error: Getter not found:" continuously show up

### ISSUE THREAD

**Issue by hoangph271** [fluttercommunity/flutter_launcher_icons#101] opened 2019-05-16 08:24 UTC
I used pubspec.yaml as following:

```
dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter
```

```
flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher/heart.png"
  adaptive_icon_background: #0984e3
  adaptive_icon_foreground: #e84393
```
But these error messages keep showing up, I don't know if there is anymore information I can provide

![Capture](https://user-images.githubusercontent.com/39024711/57838153-5bf1b600-77ee-11e9-885d-adc96bbe23b6.PNG)

**Comment by guyzk** [comment] 2019-05-16 09:26
Same exact issue here. The weird thing that it worked before. Bot sure what changed.

**Comment by maxlapides** [comment] 2019-05-16 18:33
Duplicate of #102 

My recommended temporary workaround is to add this to your pubspec.yaml file:

```
dependency_overrides:
  image: 2.0.7
```

**Comment by MarkOSullivan94** [comment] 2019-05-23 23:23
Should be fixed in v0.7.1 which I just published tonight 🤞

**Comment by dg76** [comment] 2019-05-24 08:12
Hi! I have tried the new version 0.7.1 and it does not show this error any more. However the created images are now different than before: They don't seem to use any antialiasing any more and look quite ugly... 😳

**Comment by MarkOSullivan94** [comment] 2019-05-24 08:34
@dg76 could you show a comparison of images before 0.7.1 and after?

**Comment by dg76** [comment] 2019-05-24 08:51
Yes, certainly, here are two examples:

![Screen Shot 2019-05-24 at 10 50 02](https://user-images.githubusercontent.com/17218461/58315403-c8357080-7e11-11e9-8ba6-f53caa8ba71f.png)

![Screen Shot 2019-05-24 at 10 49 33](https://user-images.githubusercontent.com/17218461/58315404-c8ce0700-7e11-11e9-8a32-af2262e02f16.png)

The left side was created using the old version with image 2.0.7 and the right one with version 0.7.1 and without the dependency_overrides of image 2.0.7.

**Comment by MarkOSullivan94** [comment] 2019-05-25 17:47
@dg76 reverting back to old interpolation method in 0.7.2 which I've just uploaded

**Comment by dg76** [comment] 2019-05-25 19:51
Unfortunately the colors are wrong now:

![Screen Shot 2019-05-25 at 21 48 59](https://user-images.githubusercontent.com/17218461/58374024-25771200-7f37-11e9-8bed-e66a11751da3.png)

Looks as if they are inverted or so? 🤔

**Comment by MarkOSullivan94** [comment] 2019-05-26 09:14
Due to a change in the image dependency - I've submitted an issue to see if it would be possible to get an option to specify to use the old color format: https://github.com/brendan-duncan/image/issues/124

**Comment by brendan-duncan** [comment] 2019-05-27 02:58
I'm looking into making the image library work better for this usage.

**Comment by brendan-duncan** [comment] 2019-05-27 04:08
The Image library 2.1.3 has the internal color format switched back to the way it was before, #AABBGGRR.

**Comment by dg76** [comment] 2019-05-29 10:05
Yes, now it seems to generate the correct icons. Thank you very much! 😊

**Comment by hoangph271** [comment] 2019-07-01 03:44
`I wasn't this issue closed...?`

**Closed** 2019-09-06 19:05 UTC
