### ISSUE TITLE
app icon color was different while i generate icons 

### ISSUE THREAD

**Issue by pmrajani** [fluttercommunity/flutter_launcher_icons#98] opened 2019-05-09 12:28 UTC
Here is my code:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#ffffff"

**It is generating slightly different color instead of my actual logo for app.**

**Comment by inceptusp** [comment] 2019-05-10 05:12
I am having the same issue, look the attached files...
Original: ![Original](https://user-images.githubusercontent.com/17789155/57504004-118da800-72c9-11e9-8014-b2343e6cd8bd.png)
 Generated: ![Generated](https://user-images.githubusercontent.com/17789155/57504005-12263e80-72c9-11e9-937a-8c0b9959c808.png)

**Comment by pmrajani** [comment] 2019-05-10 10:04
Yes same with me. 
Admin can you please look at this?

**Comment by skybur** [comment] 2019-05-10 11:52
It seems this is caused by an update to the `image` dependency. After I changed the `image` package version to 2.0.7 my icon color is correct.
You can change it by navigating to this package folder in pub_cache

**Comment by Inovactio** [comment] 2019-05-10 13:08
I am having the same issue and change the image package version to 2.0.7 doesn't work

**Comment by HelgeSverre** [comment] 2019-05-10 13:12
Having the same issue, the original color is 
#EB6F93
The generated color is: #936FEB

**Comment by skybur** [comment] 2019-05-10 13:16
@Inovactio you need to force the version to 2.0.7.
This is the current pubspec for this package
```
dependencies: 
image: "^2.0.0"
```
You need to change ` "^2.0.0"` to `"2.0.7"

@HelgeSverre yup that's because the `image` package updated the position of ARGB.
From the version 2.0.8. changelog
```
- Use #AARRGGBB for colors instead of ##AABBGGRR, to be compatible with Flutter image class.
```

**Comment by HelgeSverre** [comment] 2019-05-10 13:22
Thanks for the quick fix @skybur, that fixed the issue for now.

**Comment by mykdavies** [comment] 2019-05-10 13:26
Thanks @skybur, perfect timing as I just hit this too!

To be explicit for anyone else following this, I edited  ~/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/pubspec.yaml to read:
`dependencies:
  image: "2.0.7" #<--- No "^"! Specific version only!
  args: "^1.5.0"
 `
and did a `flutter packages get`
then ran `flutter packages pub run flutter_launcher_icons:main` again.

**Comment by HelgeSverre** [comment] 2019-05-10 13:28
You can also just set the specific version in your ```pubspec.yaml``` file, like so:
```
dev_dependencies:
  image: 2.0.7 # <- Put this here
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/Tjommi_app-icon.png"
  adaptive_icon_background: "#EB6F93"


```

**Comment by mykdavies** [comment] 2019-05-10 13:34
Thanks @HelgeSverre, that's a bit neater!

**Comment by scarings** [comment] 2019-05-14 03:27
> You can also just set the specific version in your `pubspec.yaml` file, like so:
> 
> ```
> dev_dependencies:
>   image: 2.0.7 # <- Put this here
>   flutter_launcher_icons: "^0.7.0"
>   flutter_test:
>     sdk: flutter
> 
> flutter_icons:
>   android: true
>   ios: true
>   image_path: "assets/icon/app-icon.png"
>   adaptive_icon_background: "#EB6F93"
> ```

Same issue, not working for me :(
```
image: "^2.0.7"
flutter_launcher_icons: ^0.7.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

```

**Comment by HelgeSverre** [comment] 2019-05-14 06:48
@scarings You've specified ```image: "^2.0.7"``` instead of ```image: "2.0.7``` (Notice the ^)

**Comment by florix91** [comment] 2019-05-15 13:09
Will this be fixed? Not everyone comes here to check this.

**Comment by DoubleHub** [comment] 2019-05-17 09:03
> @Inovactio you need to force the version to 2.0.7.
> This is the current pubspec for this package
> 
> ```
> dependencies: 
> image: "^2.0.0"
> ```
> 
> You need to change ` "^2.0.0"` to `"2.0.7"`
> 
> @HelgeSverre yup that's because the `image` package changed the position of ARGB.
> From the version 2.0.8. changelog
> 
> ```
> - Use #AARRGGBB for colors instead of ##AABBGGRR, to be compatible with Flutter image class.
> ```

Thank you! I was searching a solution + explanation and you offered both, amazing.

**Comment by TheBestMoshe** [comment] 2019-05-17 19:48
I had this issue as well. Pinning the image dependency worked. Thanks.

**Comment by surveshoeb** [comment] 2019-05-20 12:04
> You can also just set the specific version in your `pubspec.yaml` file, like so:
> 
> ```
> dev_dependencies:
>   image: 2.0.7 # <- Put this here
>   flutter_launcher_icons: "^0.7.0"
>   flutter_test:
>     sdk: flutter
> 
> flutter_icons:
>   android: true
>   ios: true
>   image_path: "assets/icon/app-icon.png"
>   adaptive_icon_background: "#EB6F93"
> ```

Worked

**Comment by sante85** [comment] 2019-05-21 22:10
+1

**Comment by MarkOSullivan94** [comment] 2019-05-23 23:39
Should be fixed in latest version v0.7.1 🤞

**Comment by uxartur** [comment] 2019-05-26 07:51
Same problem with version "flutter_launcher_icons: ^0.7.2".

**Comment by MarkOSullivan94** [comment] 2019-05-26 08:45
@uxartur check out @skybur's post above which should help, the issue is related the image package update.

**Comment by brendan-duncan** [comment] 2019-05-26 17:44
Sorry about the problems. Seems changing the color order caused more problems than good. The Image getBytes and fromBytes methods do let you specify the color order. For example, `Image.fromBytes(canvas.width, canvas.height, imageData.data, format: Format.rgba)` and `image.getBytes(format: Format.rgba)` will ensure the colors are encoded the way that seems to be expected by this package. I'll investigate what repercussions changing the default back will be.

**Comment by ilorivero** [comment] 2019-05-26 21:16
I have the same issue here. The image below shows the iOS iconset. The only correct image is the last one (the blue background one). The others have inverted colors.

![image](https://user-images.githubusercontent.com/19409404/58387224-cd491a00-7fe1-11e9-9e29-4368c56fc9df.png)

I used these config:

`flutter_icons:
    ios: true
    android: true
    image_path: "assets/launcher/iconesq.png"
    image_path_ios: "assets/launcher/iconesq.png"
    image_path_android: "assets/launcher/iconesq.png"
    adaptive_icon_background: "assets/launcher/iconesqback.png"
    adaptive_icon_foreground: "assets/launcher/iconesqfor.png"`

On Android, same issue using separete foreground and background images:

![image](https://user-images.githubusercontent.com/19409404/58387255-3e88cd00-7fe2-11e9-90b6-a04c8f1f4aff.png)

Thanks for any help!

**Comment by c0h1b4** [comment] 2019-05-27 02:41
pubspec.yaml:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app-icon.png"

Didn't even use adaptive_icon_background option, but with adaptive_icon_background #ffffff, get same result.

Original image:
![icon](https://user-images.githubusercontent.com/253084/58392252-807c3800-800f-11e9-8939-ffcfaa887932.png)

Generated image:
![ic_launcher](https://user-images.githubusercontent.com/253084/58392274-9e499d00-800f-11e9-903f-5fd94b16bbe5.png)

**Comment by brendan-duncan** [comment] 2019-05-28 04:47
I changed the default color order to the way it was before, released in version 2.1.3 of the image library.

**Comment by skybur** [comment] 2019-05-28 05:10
Yep, just tried and the color is correct. Thanks @brendan-duncan

**Closed** 2019-09-04 08:30 UTC

**Comment by MohammadOsmankhan** [comment] 2021-05-24 13:10
sarmayah imac$ flutter pub run flutter_launcher_icons:main
Android minSdkVersion = 16
Creating default icons Android
Overwriting the default Android launcher icon with a new icon
Creating adaptive icons Android
Overwriting default iOS launcher icon with new icon
I have this problem

**Comment by MohammadOsmankhan** [comment] 2021-05-24 13:20
dev_dependencies:
  image: 2.0.7
  flutter_widget_from_html_core: ^0.5.2
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  #image_path_android: "assets/luncher.png"
  #image_path_ios: "assets/luncher1.png"
  image_path: "assets/luncher1.png"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/luncher1.png"
  adaptive_icon_background: "assets/backgroundimg.png"
