### ISSUE TITLE
WEB Support

### ISSUE THREAD

**Issue by sem1colon** [fluttercommunity/flutter_launcher_icons#209] opened 2020-10-11 20:16 UTC
Is it supported for web?

**Comment by llucax** [comment] 2020-10-12 07:44
duplicate of #126

**Comment by bean5** [comment] 2020-10-13 21:59
Please close as duplicate.

**Comment by bean5** [comment] 2020-10-13 22:00
@slightfoot can you close this? It is a duplicate.

**Comment by RatakondalaArun** [comment] 2022-08-01 16:08
This feature is added in #374

**Closed by RatakondalaArun** 2022-08-01 16:08 UTC
Labels: improvement
