### ISSUE TITLE
Replace web\icons

### ISSUE THREAD

**Issue by dgofman** [fluttercommunity/flutter_launcher_icons#294] opened 2021-10-21 17:42 UTC
Please replace icons in web\icons when defined

flutter_icons:
  image_path: web/favicon.png
  remove_alpha_ios: false
  android: true
  ios: true
  **web: true**

**Comment by dvorapa** [comment] 2021-12-21 11:09
Duplicate of #126

**Comment by RatakondalaArun** [comment] 2022-08-01 16:16
This support is added with #374

**Closed by RatakondalaArun** 2022-08-01 16:16 UTC
Labels: improvement
