### ISSUE TITLE
ERROR: InvalidConfigException

### ISSUE THREAD

**Issue by jeevankoiri10** [fluttercommunity/flutter_launcher_icons#391] opened 2022-07-30 16:06 UTC
✓ Successfully generated launcher icons
Unhandled exception:

✗ ERROR: InvalidConfigException
#1      createIconsFromArguments (package:flutter_launcher_icons/main.dart:60:7)       
#2      main (file:///C:/Users/jeeva/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.9.3/bin/main.dart:7:26)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
pub finished with exit code 255

**Comment by RatakondalaArun** [comment] 2022-07-31 07:01
@jeevankoiri10 There is a workaround for this error in https://github.com/fluttercommunity/flutter_launcher_icons/issues/384#issuecomment-1195785786

closing this as a duplicate of #384

**Closed by RatakondalaArun** 2022-07-31 07:01 UTC
Labels: duplicate
