### ISSUE TITLE
Adaptive Icon Foreground needs to have padding otherwise ends up stretching

### ISSUE THREAD

**Issue by TonySpegel** [fluttercommunity/flutter_launcher_icons#96] opened 2019-05-01 16:31 UTC
I'm having trouble getting the setup right:
Using the following settings:
```
flutter_icons:
  android: "launcher_icon"
  image_path: "lib/res/pizza.png"
  adaptive_icon_background: "#ffe082"
  adaptive_icon_foreground: "lib/res/pizza.png"
```
Produces this Icon
![59079172_357618678208560_5351818065891819520_n](https://user-images.githubusercontent.com/1145514/57028051-50bf5780-6c3e-11e9-88cf-e2c51faccd6e.png)

This isn't the desired output because this setting:
```
flutter_icons:
  android: "launcher_icon"
  image_path: "lib/res/pizza.png"
```
produces: 
![58698513_2161850813901475_1381109938767527936_n](https://user-images.githubusercontent.com/1145514/57028102-85331380-6c3e-11e9-9dde-2dae33ac82b8.png)

I've found a related issue here: https://github.com/fluttercommunity/flutter_launcher_icons/issues/79

Anyway setting a adaptive_icon_background results in a way too big Icon the desired output is like the second Icon but with a background.
I'm not sure if I should pick one of the images produced by this tool or choosing the source image located in: ```lib/res/pizza.png```. Choosing a produced image just results in the same way too big Icon (or a blurry one choosing a lower resolution)

How do I produce an Icon as seen like in the second image but with a background?

Oh and also:
Removing settings as I did here, so deleting ```adaptive_icon_background``` & ```adaptive_icon_foreground``` and rerunning the tools does nothing, the settings generated are still there but should be removed.

**Comment by taliptako** [comment] 2019-05-03 01:02
I had the same issue right now and figured out that in the example foreground image there are paddings before exact icon as seen below
![Screenshot from 2019-05-03 03-59-23](https://user-images.githubusercontent.com/2073785/57115502-f3b7c480-6d57-11e9-975d-e216da6348ce.png)
They are transparent padding but they affect how an image will be aligned on background image 
So if you add some padding to your foreground image like this it will be fine.
But lets ask the author why this is like that 
@MarkOSullivan94 Are you aware of this situation ? if not why we need to add paddings like that

**Comment by enricobenedos** [comment] 2019-05-06 12:16
We had the same issue at the moment

**Comment by cudak01** [comment] 2019-05-18 08:25
I can confirm that the same is happening to me.
This should be the result:
![android1024](https://user-images.githubusercontent.com/43202228/57966812-40ee8580-7957-11e9-800e-23e9a80aeca5.png)

And that is the actual app icon on Android, when using adaptive foreground and background:
![Screenshot_20190518-102213](https://user-images.githubusercontent.com/43202228/57966806-29af9800-7957-11e9-9015-ce22924c79d9.png)

**Comment by MarkOSullivan94** [comment] 2019-05-23 23:46
Thanks for reporting this!

The best work around is to add the padding like the example image for now until a solution can be found to handle it better.

**Comment by jfrsbg** [comment] 2019-07-02 19:57
I'm getting the same issue by now. Other thing is that once you set adaptive_icon_background and adaptive_icon_foreground you can't change your icon anymore because the commands do not update the icons and even not overwrite them. By now i have double issues, plus this that i described. I can't test the workarroud "add the padding into icon" because i cant update the icon anymore. is there a way to make a "flutter clean icons" in my project for me at least test this solution?

**Comment by herrmartell** [comment] 2019-07-24 16:54
@jfrsbg Just go to android > app > src > main > res and delete all the drawable-dpi folders (except for the plain drawable folder), and the mipmap-any folder. Those folders contain the files for the adaptive icon, and without them Android just uses the regular icon.

**Comment by gisinator** [comment] 2019-07-26 11:36
Unfortunately I'm facing the same issue. Adding a padding, exactly like in the example, didnt solve the problem. It seems the foreground element gets cut out and fills 100% of height and width of the final icon. Do you guys have any new workarounds? :)

**Comment by enricobenedos** [comment] 2019-07-26 12:07
At the moment I'm using this configuration sucessfully
```dart
flutter_icons:

  ios: true
  android: "launcher_icon"
  image_path: "assets/launcher/icon.png"
  #image_path_ios: "assets/launcher/icon.png"
  #image_path_android: "assets/launcher/icon.png"
  #adaptive_icon_background: "assets/launcher/background.png"
  #adaptive_icon_foreground: "assets/launcher/foreground.png"
```

**Comment by gisinator** [comment] 2019-07-26 20:28
So basically you're not using the adaptive part at all, am I right? How does your original icon.png look like? Did you round the corners manually?

**Comment by enricobenedos** [comment] 2019-07-27 09:23
Yes you are right, I am not using the adaptive part. Unfortunately I cannot share the apps icons with you because they are private projects. But I have simply produced them using this guide: [Add Launcher Icon - Medium](https://medium.com/@psyanite/how-to-add-app-launcher-icons-in-flutter-bd92b0e0873a ). The icons are simply 900x900 without rounded corners. Very similar to @taliptako example.

**Comment by TonySpegel** [comment] 2019-07-27 13:35
Is this relevant to the Bug I have opened?

Am Sa., 27. Juli 2019 um 11:23 Uhr schrieb enricobenedos <
notifications@github.com>:

**Comment by enricobenedos** [comment] 2019-07-27 15:38
I just wanted to show the “solution” I adopted waiting for the bug fix.

**Comment by TonySpegel** [comment] 2019-07-28 12:30
Sorry, did not want to come across as rude :) glad that you provided a Solution. I think we've got a couple of workarounds here which is good. Let's keep this open until it really is fixed :)

**Comment by jeffsieu** [comment] 2019-09-22 05:47
@taliptako @MarkOSullivan94 According to [Android Developer guidelines](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive):

> The inner 72 x 72 dp of the icon appears within the masked viewport.
The system reserves the outer 18 dp on each of the 4 sides to create interesting visual effects, such as parallax or pulsing.

The reason why the foreground image seems to be cropped is because the adaptive icon mechanism makes use of the outer margins of the image to display parallax effects (i.e. upon dragging). **Only 66% of the original image will be shown** in the final, cropped version of the app icon.

A useful illustration from a [related Medium post](https://medium.com/google-design/designing-adaptive-icons-515af294c783):
 ![](https://miro.medium.com/max/324/1*d3ieGM2uVdKjrlF9y-G-0w.png)

A possible workaround will be to add an optional parameter `adaptive_icon_padding: true/false` in `pubspec.yaml` to add padding to the foreground image to ensure it's within the safe zone.

**Comment by bretie** [comment] 2019-10-05 18:50
I'm having this same issue. I've made a custom version of my android icon with no background and added padding to all sides. Still is stretched and it doesn't look good.

**Comment by k00na** [comment] 2019-10-25 09:40
I can confirm that @bernaferrari answer helped me as well. 

You must open the android folder of your flutter project with Android Studio, and open the menu as show bellow with the right mouse click on your the left pallate in AS: 

<img width="868" alt="Screenshot 2019-10-25 at 11 38 08" src="https://user-images.githubusercontent.com/13611208/67560874-0bc33c00-f71c-11e9-95e3-81e4f660ebfe.png">

Then do the setup for your launcher icon in AS... I've set mine foreground icon size to 66% and now it fits perfectly fine. 

![Screenshot 2019-10-25 at 11 31 53](https://user-images.githubusercontent.com/13611208/67560917-22699300-f71c-11e9-8160-30fde0948abc.png)

**Comment by talamaska** [comment] 2019-12-03 10:49
@k00na @MarkOSullivan94 @bernaferrari So, does this plugin actually tries to replicate what Android Studio is doing? And if it does, do we want full support of the the little settings on that screen as setting in the pubspec? And I think I want them, it that case should it still be a CLI build runner or A full blown desktop flutter app for generating app icons? Cause I feel having a preview and a slider for the scaling are necessairy. Just thinking out loud here. Maybe another thread for this?

**Comment by elmariocarlos** [comment] 2020-02-01 19:16
@MarkOSullivan94 so any news on when the plugin might get the necesary accomodations to get the expected results? This plugin originally helped us a lot, but after the adaptive icon and foreground requirement from Google, this extra step seems like a pedal backwards.

**Comment by Ahmadre** [comment] 2020-04-10 21:53
![maxresdefault](https://user-images.githubusercontent.com/18512224/79025534-5891b680-7b86-11ea-9320-a4298cf94549.jpg)

😆not working yet. Every project, every icon doesn't fit...

**Comment by Ahmadre** [comment] 2020-04-11 00:47
Guys I think all of you, who got problems just didn't understand exactly how to provide icons for android: 

My config:

```dart
flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/mataku_logo.png"
  adaptive_icon_padding: true
  adaptive_icon_background: "assets/images/adaptive_mataku_logo_bg.png"
  adaptive_icon_foreground: "assets/images/adaptive_mataku_logo_fg.png"
```

My Background:
![adaptive_mataku_logo_bg](https://user-images.githubusercontent.com/18512224/79031375-9dc1e280-7b9e-11ea-893c-c58ea62b0180.png)

My Foreground:
![adaptive_mataku_logo_fg](https://user-images.githubusercontent.com/18512224/79031380-a31f2d00-7b9e-11ea-8621-3161028aab54.png)

My icon on android:
<img width="67" alt="Bildschirmfoto 2020-04-11 um 02 47 01" src="https://user-images.githubusercontent.com/18512224/79031394-b9c58400-7b9e-11ea-91e2-21ebd3f22212.png">

So I got no problems. I created my images in photoshop and I could add padding if i want to my foreground.

**Comment by damiafuentes** [comment] 2020-05-26 10:27
This issue is still happening with v0.7.5

**Comment by zxl777** [comment] 2020-05-27 01:01
Yes. This issue is still happening with v0.7.5

**Comment by knyghtryda** [comment] 2020-06-24 00:44
I just created a PR #181 to take care of this issue, at least for the foreground image (which was my use case).  Give it a go on your own fork and see what you think.  I'll add background image support shortly.

**Comment by hakankucuk** [comment] 2020-07-07 19:59
What should be minimum icon dimensions which put in to the asests directory?

**Comment by knyghtryda** [comment] 2020-07-18 18:47
> What should be minimum icon dimensions which put in to the asests directory?

if you want zero upscaling across all platforms then use 1024x1024, as the largest icon used will be the iOS app store icon at that size.  FYI play store icons are 512x512.

**Comment by codepushr** [comment] 2020-08-04 10:15
Any plans to merge this?

**Comment by brianbhsu** [comment] 2020-09-03 17:18
This issue should be pinned in the repo. If you skip setting adaptive_icon_background and adaptive_icon_foreground for an android app, it can lead to unintended effects such as the app icon appearing different (different background colors) in the overview screen vs the home screen. And in order to use the adaptive icon settings, this issue I would say is high priority since it significantly affects how the icon is displayed to the end user.

**Comment by edisonywh** [comment] 2020-09-13 15:59
Thanks @knyghtryda, tested it out and works great! This issue has been such a headache, would be great for the team to merge this.

**Comment by AlexHartford** [comment] 2020-10-09 17:22
This is still an issue, and @knyghtryda PR is still not merged. Can we make this happen please?

**Comment by als409** [comment] 2020-10-30 00:30
It is working for me like this:

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: "launcher_icon"

  assets:
    - assets/icon/icon.png

**Comment by als409** [comment] 2020-10-30 00:34
It is working for me like this:

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: "launcher_icon"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/icon.png

**Comment by als409** [comment] 2020-10-30 00:34
It is working for me like this:

`
flutter_icons:
  image_path: "assets/icon/icon.png"
  #adaptive_icon_background: "#ffe082"
  #adaptive_icon_foreground: "assets/icon/icon.png"
  android: "launcher_icon"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/deivyz-cattle-logo-app-1500.png
    - assets/icon/icon.png
`

**Comment by tirth-stasis** [comment] 2021-02-17 07:33
why is it still not merged?

**Comment by mdarif** [comment] 2021-03-24 14:46
Now we are in March 2021 and the issue is still exist.

**Comment by hayatbangash55** [comment] 2021-03-25 09:42
The issue still exists....

**Comment by DevDorrejo** [comment] 2021-04-19 06:41
This issue still.

**Comment by fabiancrx** [comment] 2021-06-21 19:04
The issue still exists because none of us has fixed it, this is OSS for the good and the bad, and complaining won't fix it.

**Comment by Aulig** [comment] 2021-06-21 19:09
> 
> 
> The issue still exists because none of us has fixed it, this is OSS for the good and the bad, and complaining won't fix it.

Totally agree. However, there is a PR #181 which is just waiting to get merged. Anyone who urgently needs this can just use that version.

**Comment by PrimeAnteneh** [comment] 2021-07-01 17:11
This is still an issue

**Comment by blarz-bix** [comment] 2021-07-02 15:11
I just created an image of 900x900 and it worked only with this. 

Version:   flutter_launcher_icons: "^0.9.0"

```
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher/undebtme-logo.png"
  adaptive_icon_background: "assets/images/launcher/background.png" 
  adaptive_icon_foreground: "assets/images/launcher/undebtme-logo.png" 
```
![image](https://user-images.githubusercontent.com/75634952/124294723-41394300-db15-11eb-99b6-5212e367f6c2.png)

**Comment by DevDorrejo** [comment] 2021-07-02 17:21
> I just created an image of 900x900 and it worked only with this. I tried with a smaller image and it didn't work.
> 
> Version: flutter_launcher_icons: "^0.9.0"
> 
> ```
> flutter_icons:
>   android: true
>   ios: true
>   image_path: "assets/images/launcher/undebtme-logo.png"
>   adaptive_icon_background: "assets/images/launcher/background.png" 
>   adaptive_icon_foreground: "assets/images/launcher/undebtme-logo.png" 
> ```
> 
> ![image](https://user-images.githubusercontent.com/75634952/124294723-41394300-db15-11eb-99b6-5212e367f6c2.png)

looks fine, but is not centered, we need an improve on flutter launcher icon.

**Comment by ariefwijaya** [comment] 2021-09-10 05:25
Please , any updates ?

**Comment by pablohs1986** [comment] 2021-09-28 08:07
>  image_path: "assets/images/launcher/undebtme-logo.png"
>   adaptive_icon_background: "assets/images/launcher/background.png" 
>   adaptive_icon_foreground: "assets/images/launcher/undebtme-logo.png"

This works for me !! Thanks!!!

**Comment by TuupleMasterAndroid** [comment] 2021-12-22 14:48
issue not solve December 21

**Comment by erperejildo** [comment] 2021-12-22 21:21
> issue not solve December 21

Yeah, but that was yesterday. Today... oh well, today still  not fixed

**Comment by adminant** [comment] 2022-01-06 11:18
Are there any news on this? 
And the problem is that on round Android icon this plugin produces square inside(

**Comment by milanobrenovic** [comment] 2022-01-13 16:52
This is still not fixed...

**Comment by daniel-hopkins** [comment] 2022-02-18 00:40
I created a [psd template](https://github.com/fluttercommunity/flutter_launcher_icons/files/8093163/launcher_icon_android.psd.zip) that has guides for creating the adaptive icon.
What I did was to save my logo layer a transparent png, and save the clean background separately.
It loads well onto android for me, but would love if someone else wants to try it out.
```
adaptive_icon_background: "dev_assets/my_icon_900x900_background.png"
adaptive_icon_foreground: "dev_assets/my_icon_900x900.png"
```
It certainly doesn't solve the issue, but at least provides a workaround. 
![Screenshot_20220217-173728_2](https://user-images.githubusercontent.com/1554954/154595161-ad1a1977-a498-4526-b892-6288bd829586.png)
![Screenshot_20220217-174148_2](https://user-images.githubusercontent.com/1554954/154595163-142ade2f-770a-4cb0-a86d-55a58266d717.png)
[launcher_icon_android.psd.zip](https://github.com/fluttercommunity/flutter_launcher_icons/files/8093163/launcher_icon_android.psd.zip)

**Comment by erperejildo** [comment] 2022-02-20 08:53
awesome support! (said no one)

**Comment by DevDorrejo** [comment] 2022-03-07 23:27
> awesome support! (said no one)

so, which are the minimum?

**Comment by erperejildo** [comment] 2022-03-08 09:57
> > awesome support! (said no one)
> 
> so, which are the minimum?

that was irony

**Comment by Binozo** [comment] 2022-03-12 21:28
Sadly, I have the same issue too

**Comment by scorninpc** [comment] 2022-03-21 18:10
I'm facing sabe problem but only on list of apps 

OK on docker
![image](https://user-images.githubusercontent.com/2607849/159336950-6730bd21-c6c7-40a4-b46f-ae1758f77eec.png)

But problem on list of apps 
![image](https://user-images.githubusercontent.com/2607849/159337022-9aac99b7-2eca-41ce-8ef4-93cb019daf72.png)

**Comment by galaxiarmy** [comment] 2022-03-28 09:29
https://www.youtube.com/watch?v=eMHbgIgJyUQ

**Comment by scorninpc** [comment] 2022-03-28 10:48
> https://www.youtube.com/watch?v=eMHbgIgJyUQ

Ok, but sorry. If we open a issue for the plugin works, that's because we don't want to do this manually. This plugin has a lot potential.

**Comment by ivirtex** [comment] 2022-04-02 09:49
What happened to this package? Not a single commit has been made for over 1.5 years.

**Comment by JulianOrozcoC** [comment] 2022-04-25 23:45
Any update? Having the same problem

**Comment by FiKa404** [comment] 2022-09-21 18:24
Problem still exist !

**Comment by masteradit** [comment] 2022-10-10 06:01
Any updates on this? It has been almost 3.5 years, and this issue is still there!

**Comment by mathiasgodwin** [comment] 2022-10-22 09:22
I'm facing this issue as well. With my observation, I feel this issue is a bit difficult to deal with, it couldn't have been easy for them to neglect our complaint here, even @felangel said something like this about a year ago while considering this on **very_good_cli**. I also think the package maintainers are finding it hard to tell us to find a workaround for the time being while they're probably working on it.

**Comment by Kianto** [comment] 2022-11-23 16:58
I found a solution:

After generating your icon with adaptive_icon_foreground then modify the file: android/.../res/mipmap-anydpi-v26/`ic_launcher.xml` by `android:inset="16%"`
(Open Android module to review the image).
To me 16% is ok, you can check this number and change it.

```
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
  <background android:drawable="@color/ic_launcher_background"/>
  <foreground>
    <inset
      android:drawable="@drawable/ic_launcher_foreground"
      android:inset="16%" />
  </foreground>
</adaptive-icon>
```

Ref: https://medium.com/androiddevelopers/implementing-adaptive-icons-1e4d1795470e

**Comment by julienripet** [comment] 2022-12-02 09:51
> I found a solution:
> 
> After generating your icon with adaptive_icon_foreground then modify the file: android/.../res/mipmap-anydpi-v26/`ic_launcher.xml` by `android:inset="16%"` (Open Android module to review the image). To me 16% is ok, you can check this number and change it.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
>   <background android:drawable="@color/ic_launcher_background"/>
>   <foreground>
>     <inset
>       android:drawable="@drawable/ic_launcher_foreground"
>       android:inset="16%" />
>   </foreground>
> </adaptive-icon>
> ```
> 
> Ref: [medium.com/androiddevelopers/implementing-adaptive-icons-1e4d1795470e](https://medium.com/androiddevelopers/implementing-adaptive-icons-1e4d1795470e)

Worked great, thanks for the solution

**Comment by rafaellop** [comment] 2022-12-18 00:36
There should be a parameter in `pubspec.yaml`  to specify the inset value for the inset as in the @Kianto example. Now each time I regenerate icons using the CLI the changes to the `android/.../res/mipmap-anydpi-v26/ic_launcher.xml` are lost.

**Comment by kohj1018** [comment] 2023-03-02 20:14
> 해결책을 찾았습니다.
> 
> Adaptive_icon_foreground로 아이콘을 생성한 후 다음 파일을 수정합니다. android/.../res/mipmap-anydpi-v26/ `ic_launcher.xml`by `android:inset="16%"` (Open Android module to review the image). 나에게 16%는 괜찮습니다. 이 숫자를 확인하고 변경할 수 있습니다.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
>   <background android:drawable="@color/ic_launcher_background"/>
>   <foreground>
>     <inset
>       android:drawable="@drawable/ic_launcher_foreground"
>       android:inset="16%" />
>   </foreground>
> </adaptive-icon>
> ```
> 
> 참조: https://medium.com/androiddevelopers/implementing-adaptive-icons-1e4d1795470e

This really worked for me.

Everyone seems to be able to use this solution.
For me, 28% was appropriate.
Thank you very much for your solution.

**Comment by theachoem** [comment] 2023-07-25 17:47
Hope this help fix android [adaptive icon](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) padding problems. Tested with Android/IOS/MacOS/Web.

![image](https://github.com/fluttercommunity/flutter_launcher_icons/assets/29684683/dd81b1a7-3c5d-4a86-8d78-10d9643ed8a2)

> For other platforms, we can use IOS logo.

**Comment by alvincentino** [comment] 2023-07-31 04:24
> 

This worked for me also, for me it was 24 for the insets. thanks

**Comment by alvincentino** [comment] 2023-07-31 04:25
> > I found a solution:
> > After generating your icon with adaptive_icon_foreground then modify the file: android/.../res/mipmap-anydpi-v26/`ic_launcher.xml` by `android:inset="16%"` (Open Android module to review the image). To me 16% is ok, you can check this number and change it.
> > ```
> > <?xml version="1.0" encoding="utf-8"?>
> > <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
> >   <background android:drawable="@color/ic_launcher_background"/>
> >   <foreground>
> >     <inset
> >       android:drawable="@drawable/ic_launcher_foreground"
> >       android:inset="16%" />
> >   </foreground>
> > </adaptive-icon>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ref: [medium.com/androiddevelopers/implementing-adaptive-icons-1e4d1795470e](https://medium.com/androiddevelopers/implementing-adaptive-icons-1e4d1795470e)
> 
> Worked great, thanks for the solution

This worked for me also, for me it was 24 for the insets. thanks

**Comment by sha3rawi33** [comment] 2023-08-19 21:46
> I found a solution:
> 
> After generating your icon with adaptive_icon_foreground then modify the file: android/.../res/mipmap-anydpi-v26/`ic_launcher.xml` by `android:inset="16%"` (Open Android module to review the image). To me 16% is ok, you can check this number and change it.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
>   <background android:drawable="@color/ic_launcher_background"/>
>   <foreground>
>     <inset
>       android:drawable="@drawable/ic_launcher_foreground"
>       android:inset="16%" />
>   </foreground>
> </adaptive-icon>
> ```
> 
> Ref: https://medium.com/androiddevelopers/implementing-adaptive-icons-1e4d1795470e

Thanks, worked like a charm! ❤️‍🔥

**Comment by legenduzo** [comment] 2023-09-10 12:52
> I found a solution:
> 
> After generating your icon with adaptive_icon_foreground then modify the file: android/.../res/mipmap-anydpi-v26/`ic_launcher.xml` by `android:inset="16%"` (Open Android module to review the image). To me 16% is ok, you can check this number and change it.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
>   <background android:drawable="@color/ic_launcher_background"/>
>   <foreground>
>     <inset
>       android:drawable="@drawable/ic_launcher_foreground"
>       android:inset="16%" />
>   </foreground>
> </adaptive-icon>
> ```
> 
> Ref: https://medium.com/androiddevelopers/implementing-adaptive-icons-1e4d1795470e

I had the error: 
Android inset not allowed here
with this solution.

I think the best workaround in the meantime is to specify your dimensions as shown in @theachoem's example.

**Comment by amorenew** [comment] 2023-11-02 18:11
According to Google Adaptive Icons, you need a safe area with about 33% padding, while background could fill the whole area
![image](https://github.com/fluttercommunity/flutter_launcher_icons/assets/2842459/b222072e-0aec-4f2f-96a6-aad3b1bb7a2e)

**Comment by GentiShtjefni** [comment] 2024-03-20 14:34
I have an issue that in android shows the icon with some white background but in ios it shows the icon with the white background, like android, but also another black background
![image](https://github.com/fluttercommunity/flutter_launcher_icons/assets/84448161/89fd8d48-5e72-41c3-8752-3b7dd79454f6)
I only want the white background like in android. Any solutions?

**Comment by InkyGoose** [comment] 2024-04-29 13:56
I found a solution. The design specifications for the Google icon provide a grid for creating icons. I created a 1024x1024 canvas and filled the entire canvas with this grid (I increased the width of the lines for clarity). Using this canvas as the foreground and a blank canvas as the background to generate icons, the results can be seen as follows. 
![20240429214935](https://github.com/fluttercommunity/flutter_launcher_icons/assets/142213025/e06d2dbc-192f-48cd-b441-e45595adbfda)
![20240429215102](https://github.com/fluttercommunity/flutter_launcher_icons/assets/142213025/2757f7de-0c60-4e05-b7e5-cc7472a65779)
Clearly, the visible part of the icon is the inscribed square of the larger circle. Therefore, when creating an icon, **as long as it is placed within the inscribed square, the problem of the icon being too large can be avoided**. In other words, leaving enough blank space around the edges can solve the problem, and how much space to leave can be determined by the grid.

**Comment by lehoangbaochung** [comment] 2024-06-02 02:58
let's fix it !

**Comment by erperejildo** [comment] 2024-06-02 14:36
This issue was open more than 5 years ago. 
- Is this repo abandoned?
- What's the problem to fix this?
- Any other option out there?

**Comment by LOCKEDFILE** [comment] 2024-06-12 01:43
After reading @Kianto comment, I requested a PR for those who find it bothersome to change it manually every time. The default value for the inset is 16.


**PR #563**
or
~~~
  flutter_launcher_icons: 
    git: https://github.com/LOCKEDFILE/flutter_launcher_icons.git
~~~

> I found a solution:
> 
> After generating your icon with adaptive_icon_foreground then modify the file: android/.../res/mipmap-anydpi-v26/`ic_launcher.xml` by `android:inset="16%"` (Open Android module to review the image). To me 16% is ok, you can check this number and change it.
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
>   <background android:drawable="@color/ic_launcher_background"/>
>   <foreground>
>     <inset
>       android:drawable="@drawable/ic_launcher_foreground"
>       android:inset="16%" />
>   </foreground>
> </adaptive-icon>
> ```
> 
> Ref: https://medium.com/androiddevelopers/implementing-adaptive-icons-1e4d1795470e

**Closed** 2024-09-21 15:29 UTC
Labels: help wanted, needs investigating
