### ISSUE TITLE
[BUG] Incorrectly issues success message when icon file not found

### ISSUE THREAD

**Issue by araruna** [fluttercommunity/flutter_launcher_icons#250] opened 2021-05-22 04:40 UTC
### :information_source: Info

Version: `0.8.0`

### :speech_balloon: Description

When I inform a file path that does not exist, the output includes a message stating that the generation went successfully, followed by a stack trace.

Output:
```text
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.8.0)                               
  ════════════════════════════════════════════
  
• Creating default icons Android

✓ Successfully generated launcher icons
Unhandled exception:
FileSystemException: Cannot open file, path = './assets/icon/icon.png' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File.openSync (dart:io/file_impl.dart:479:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:539:18)
#3      createDefaultIcons (package:flutter_launcher_icons/android.dart:35:50)
#4      createIconsFromConfig (package:flutter_launcher_icons/main.dart:99:5)
#5      createIconsFromArguments (package:flutter_launcher_icons/main.dart:58:7)
#6      main (file:///home/araruna/.flutter/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.8.1/bin/main.dart:6:3)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
pub finished with exit code 255
```

### :scroll: Pubspec.yaml

Relevant part (the correct filename was `cesta.png`):
```text
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
```

**Comment by MarkOSullivan94** [comment] 2021-07-25 20:57
@araruna can you try this again with the latest version (0.9.1) please?

**Comment by MarkOSullivan94** [comment] 2021-07-25 21:07
Duplicate of: https://github.com/fluttercommunity/flutter_launcher_icons/issues/225

**Closed by MarkOSullivan94** 2021-07-25 21:07 UTC
