### ISSUE TITLE
[BUG] - Multitasking logo background color error

### ISSUE THREAD

**Issue by Macacoazul01** [fluttercommunity/flutter_launcher_icons#287] opened 2021-09-14 17:42 UTC
### :information_source: Info

Version: `e.g. v0.9.2`

### :speech_balloon: Description

The background color of the app on the store/home menu is different than the one on the multitasking tab. The first one is white (ok), and the second is blue.

![home](https://user-images.githubusercontent.com/57464965/133307299-efe32545-06af-43eb-b5c6-2d5115f1e572.png)
![Inkedmenu_LI](https://user-images.githubusercontent.com/57464965/133307304-798be53e-3c8d-4a50-8cd9-1a668f44883b.jpg)
![multitask](https://user-images.githubusercontent.com/57464965/133307311-1a6f0678-1ff5-400b-b208-564f10040284.png)

### :scroll: Pubspec.yaml

```
name: oioio
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-96.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
 android: true
 ios: true
 image_path: "images/isotipo.png"
 remove_alpha_ios: true
 adaptive_icon_foreground: "#ffffff" 
flutter:
  uses-material-design: true
```

**Comment by Macacoazul01** [comment] 2022-06-29 23:37
@RatakondalaArun i'm still having this issue on 0.9.3 version

**Comment by Macacoazul01** [comment] 2022-06-30 15:11
It's relevant to say that the error happens on android 11 too (hadn't tested on other versions)

**Comment by RatakondalaArun** [comment] 2022-06-30 15:17
Thanks,

Since there were lot of changes in flutter after this issue is created, I think it would be better if we can check it with new project.

**Comment by Macacoazul01** [comment] 2022-06-30 17:19
It's exactly the same behavior, now with flutter 3.0.3.

Like i've said, i ran the project with 0.9.3 that you guys released this month and it's still happening

**Comment by RatakondalaArun** [comment] 2022-06-30 17:41
Thank for the info, I will look into it as soon as possible

**Comment by Macacoazul01** [comment] 2022-07-02 15:37
@RatakondalaArun
[erro.zip](https://github.com/fluttercommunity/flutter_launcher_icons/files/9033228/erro.zip)

**Comment by Policy56** [comment] 2022-07-05 07:16
Hi,  i got the same problem on my apps
This issue is caused by Material 3 theme

**Comment by Macacoazul01** [comment] 2022-07-07 16:18
@Policy56 it was happening before material 3. 
Did you fix on your app?

**Comment by Policy56** [comment] 2022-07-08 13:24
@Macacoazul01 , hi 
No,  this bug happens in Flutter 3.0.3 with Material 3

**Comment by Macacoazul01** [comment] 2022-07-08 16:02
> @RatakondalaArun [erro.zip](https://github.com/fluttercommunity/flutter_launcher_icons/files/9033228/erro.zip)

@Policy56 do you have any sample like this for your project running material 3 with the bug vs without material (and the bug)
maybe it'll help @RatakondalaArun

**Comment by Macacoazul01** [comment] 2022-08-06 12:28
@RatakondalaArun any expectations of this being fixed?

**Comment by RatakondalaArun** [comment] 2022-09-18 17:38
I think this feature is out of scope for flutter_launcher_icons

I don't know which property is setting this but it got something to do with the flutter theme.

<img src="https://user-images.githubusercontent.com/47482264/190920610-7e3d1094-d855-49bf-b77a-f647312f19e5.png" width="40%"></img><img src="https://user-images.githubusercontent.com/47482264/190920614-251eb57e-147f-443a-8148-fad149c60d31.png" width="40%"></img>

**Comment by Macacoazul01** [comment] 2022-09-19 17:42
@RatakondalaArun did you created an issue on flutter git?
If not, i'm gonna test here and create

**Comment by RatakondalaArun** [comment] 2022-09-20 04:56
I didn't create any issue at flutter repo
I used [flex_color_scheme](https://pub.dev/packages/flex_color_scheme) package to set the theme for my app

```dart
  static ThemeData light(BuildContext context) {
    return FlexThemeData.light(
      useMaterial3: true,
      scheme: FlexScheme.wasabi,
      subThemesData: const FlexSubThemesData(),
    );
  }
```

**Comment by Macacoazul01** [comment] 2022-09-20 22:42
> I think this feature is out of scope for flutter_launcher_icons
> 
> I don't know which property is setting this but it got something to do with the flutter theme.

@RatakondalaArun changing the theme on the counter app already generated the problem, let's see what the team says about it

**Comment by Macacoazul01** [comment] 2022-10-12 19:48
@RatakondalaArun as flutter team stated, this is the expected behavior for android and they won't change it (even being different from ios).

The solution is to add the same background color of the logo to the `color` parameter of `WidgetApp` (`MaterialApp`, `Cupertino`...).

They agree that this should be on the docs (but like its a P4 issue i doubt it'll be done on the next months).

What do you think of enforcing this here on flutter_launcher_icons?

**Closed** 2022-12-14 02:55 UTC
Labels: bug, platform:android
